services:
  - type: web
    name: menaxa-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
